version: "2"

linters:
  # See https://golangci-lint.run/usage/linters for details.
  default: none
  enable:
    - containedctx
    - fatcontext
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
    - contextcheck
run:
  skip-dirs:
    - internal/mocks